### ISSUE TITLE
Adjust timeout?

### ISSUE THREAD

**Issue by jluttine** [cmaion/polar#16]
I was syncing my V800 and it was syncing fine but suddenly got the following error:

```
lib/ruby/gems/2.6.0/gems/libusb-0.6.4/lib/libusb/dev_handle.rb:549:in `submit_transfer': error TRANSFER_TIMED_OUT (LIBUSB::ERROR_TIMEOUT)
```

I guess there was just so much to sync that it took so long that libusb timed out. Can I somehow adjust this timeout period so that it wouldn't timeout so easily? Or is there something that this polar tool could do to tell libusb that everything is fine, it's downloading just many many files. Or what do you think?

**Comment by jluttine** [comment]
It's also possible that the USB connection just failed for some reason..

**Comment by jluttine** [comment]
Hmm.. Seems to be timing out consistently after some time.

**Comment by cmaion** [comment]
Hi, this is usually due to a bad USB connection/dirty contacts.
My V800 does the same from time to time, the charging port/clamp mechanism is not to totally bullet proof in my experience (especially when it comes to data transfer, charging is less sensitive). Disconnect the watch, give the contacts a quick clean, clamp it again.

**Comment by jluttine** [comment]
Ok, thanks!
